### ISSUE TITLE
html is not defined

### ISSUE THREAD

**Issue by redox** [sitemavens/maven-algolia#13]
Hey guys, small typo in your code at https://github.com/sitemavens/maven-algolia/blob/master/front/assets/scripts/predictions.js#L79

I didn't noticed it before because the `if` condition was `false` on our blog (no featured images).

![screen shot 2014-06-12 at 08 38 12](https://cloud.githubusercontent.com/assets/29529/3254632/5cc576de-f1fc-11e3-8499-5a29588dcf6c.png)

Keep up the good work!

**Comment by gtenaschuk** [comment]
Thanks redox, we decided to exclude the thumbnail from the predictions popup for now. We will implement a plugin setting to support that in the next upgrade.
